version: 0.2

env:
  parameter-store:
      $DOCKER_URL: "/myapp/dockercredentials/dockerurl"
      $DOCKER_Username: "/myapp/dockercredentials/dockerusername"
      $DOCKER_Pass: "/myapp/dockercredentials/dockerpass"
  phases:
    install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    runtime-versions:
        java: corretto11
        #name: version
    #commands:
      #- command
   #pre_build:
     #commands:
        #- command
        #- command
    build:
     commands:
        - ./InstallJenkins.sh
        - echo "$DOCKER_Pass" | docker login -u "$DOCKER_Username" --password-stdin "$DOCKER_URL"
        - docker build -t "$DOCKER_URL/$DOCKER_Username/jenkinstest1:latest" .
        - docker push "$DOCKER_URL/$DOCKER_Username/jenkinstest1:latest"
  #post_build:
    #commands:
      # - command
      # - command
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths
