# Base image
FROM java:corretto17

# Set the working directory inside the container
WORKDIR /app

# Copy the requirements file

# Install the project dependencies


# Copy the application code into the container


# Expose the port the Flask application will be listening on
EXPOSE 8080

# Set environment variables, if necessary
# ENV MY_ENV_VAR=value

# Run the Flask application
